version: '2'

services:
  API:
    image: 'employee-states-ms.jar'
    ports:
      - "8050:8050"
    depends_on:
      PostgresSQL:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgresSQL:5432/statedb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update


  PostgresSQL:
      image: postgres
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=statedb
      healthcheck:
        test: ["CMD-SHELL","pg_isready -U postgres"]
        interval: 60s
        timeout: 5s
        retries: 5

